### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ACSoupir** [ACSoupir/Spatial-Metrics-Toolkit#1]
# Goal Items

## For Beginners
- [x] Write script to be called at the beginning to set up folder structure (create folders), possibly based on options.
- [x] Write plotting function to visualize the per-cell data (x and y for cell locations, color based on markers) - Divya
- [x] Summarize each sample for positive marker frequency and export and single csv (one row per sample)
- [x] #2
- [ ] Write README.md sections for each spatial metric implemented describing the metric and how to interpret output values.

## Functionality and Documentation
- [x] `optparse` main script to handle interacting with users and 'behind the scenes' processing
- [x] YAML option to hold variables for processing like folders, markers in per-cell data, metrics to calculate, etc
- [ ] Check whether required columns are available in the data in `data/per-cell` folder, and that the values in said columns are in correct format (i.e. 1/0 for marker positivity).
- [x] Implement at least 3 methods to derive spatial metrics.
- [x] Create plotting functions for calculated metrics to allow users to visualize.

# Nice To Have Some Day
- [ ] Allow for permutations to handle issues with sample stationarity (cells showing up evenly around the sample; different folders for results for each permutation and summarised across permutations)
- [x] Rely on SLURM or other multithreading tool to distribute jobs across nodes rather than within R
- [ ] Shiny application for users to upload data and see basic results

**Comment by ACSoupir** [comment]
Each function will take in a path to a csv file in the data/per-cell/ folder as well as the yaml list.
